### ISSUE TITLE
Package version for `manifest`

### ISSUE THREAD

**Issue by ravenouse** [thakkarparth007/copilot-inspector#5]
Hi @thakkarparth007!
Thank you so much for your effort on this great project!

I was trying to run this project locally but countered some problems with python packages. Namely, I don't have `manifest` installed and I cannot install it with `pip install manifest`. Could you provide the version of this package you used?
![截屏2022-12-31 下午7 16 58](https://user-images.githubusercontent.com/85110830/210159290-2ce9296d-20c4-41cb-9a1d-52f87e6b3050.png)

Thank you so much again!

**Comment by thakkarparth007** [comment]
Hi Zhiyong, the manifest library is called manifest-ml on pip. It can also
be found on github at https://github.com/hazyresearch/manifest
